apiVersion: v1
kind: Service
metadata:
  name: messaging-app-service
spec:
  selector:
    app: messaging-app-green   # Switch this between messaging-app-blue and messaging-app-green as needed
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP